Fixing crash for attachments
GetStream/android-chat-tutorial pull request #40
Opened 2021-02-12 18:51 UTC by leandroBorgesFerreira

Fixes crash for when users click in attachments. This style must be used so `com.google.android.material.card.MaterialCardView` can be used

2021-02-14 17:29 UTC, bychkovdmitry commented
The same should be done for java tutorial

2021-02-14 17:29 UTC, bychkovdmitry requested changes

2021-02-14 17:29 UTC, bychkovdmitry commented on samplekotlin/src/main/AndroidManifest.xml
> +        <activity android:name=".ChannelActivity"
Lets just change the base application theme to material:
`<style name="AppTheme" parent="Theme.MaterialComponents.DayNight.NoActionBar">`

2021-02-15 07:58 UTC, zsmb13 requested changes
Can we fix this inside the SDK instead of adding new code and steps to the tutorial?

2021-02-18 12:20 UTC, leandroBorgesFerreira commented
This was fixed in the SDK, I don't see the crash anymore.

2021-02-18 12:20 UTC, closed without merging